---
title: "CSCI 550 Project 1"
author: "Heather Koyuk, Muzhou Chen, Greg Martin"
date: "9/27/2022"
output: pdf_document
urlcolor: blue
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Load packages

```{r load-packages, message=FALSE}
library(tidyverse)
library(knitr)
library(lubridate)
library(psych)
```

```{r load-data, message=FALSE}
Customer_telecom <- read.csv("Customer_telecom.csv")
                             
```

## TODO: Executive Summary


## EDA

```{r eda}

num_c <- Customer_telecom %>%
  select(account.length, number.vmail.messages, total.day.minutes, total.day.calls, total.day.charge, total.eve.minutes, total.eve.calls, total.eve.charge, total.night.minutes, total.night.calls, total.night.charge, total.intl.minutes, total.intl.calls, total.intl.charge, customer.service.calls)

cor(num_c)
summary(Customer_telecom)

num_c <- num_c %>%
  select(account.length, number.vmail.messages, total.day.minutes, total.day.calls, total.eve.minutes, total.eve.calls, total.night.minutes, total.night.calls, total.intl.minutes, total.intl.calls, customer.service.calls)

minutes_c <- num_c %>%
  select(account.length, number.vmail.messages, total.day.minutes, total.eve.minutes, total.night.minutes, total.intl.minutes, customer.service.calls)

pairs(minutes_c)

calls_c <-  Customer_telecom %>%
  select(account.length, number.vmail.messages, total.day.calls, total.eve.calls, total.night.calls, total.intl.calls, customer.service.calls)
pairs(calls_c)

sums_c <- Customer_telecom %>%
  mutate(total_minutes = sum(total.day.minutes, total.eve.minutes, total.night.minutes, total.intl.minutes)) %>%
  mutate(total_calls = sum(total.day.calls, total.eve.calls, total.night.calls, total.intl.calls)) %>%
  select(account.length, number.vmail.messages, total_minutes, total_calls,  customer.service.calls)
                             
pairs(sums_c)

Customer_telecom <- Customer_telecom %>%
  mutate(churn1 = if_else(churn == "False", 0, 1))

glm.fits <- glm(
  churn1 ~ total.day.minutes,
  data = Customer_telecom, family = binomial
)
summary(glm.fits)

glm.fits1 <- glm(
  churn1 ~ account.length+ number.vmail.messages+ total.day.minutes+total.day.calls+ total.day.charge+ total.eve.minutes+ total.eve.calls+total.eve.charge+ total.night.minutes+total.night.calls+ total.night.charge+ total.intl.minutes+total.intl.calls+total.intl.charge+ customer.service.calls,
  data = Customer_telecom, family = binomial
)
summary(glm.fits1)
```


## Models

##LDA
```{r lda}
library(MASS)
library(caret)


#Randomly shuffle the data
Customer_telecom<-Customer_telecom[sample(nrow(Customer_telecom)),]

#Create 10 equally size folds
folds <- cut(seq(1,nrow(Customer_telecom)),breaks=10,labels=FALSE)

MAE=c()
mae=c()

#K-fold Cross Validation
for (i in 1:10){
  testIndexes <- which(folds==i,arr.ind=TRUE)
  test_data <- Customer_telecom[testIndexes, ]
  train_data <- Customer_telecom[-testIndexes, ]
  m_lda <- lda(churn1 ~ number.vmail.messages + total.intl.calls + customer.service.calls, data = train_data)
  m_pred <- predict(m_lda, test_data)
  conf <- table(list(predicted=m_pred$class, observed=test_data$churn1))
  confusionMatrix(conf)
  print(conf)
  mae <- c(mae, mean(abs(as.integer(m_pred$class == 1) - as.integer(test_data$churn1 == 1))))
}

MAE=c(MAE, mean(mae))
MAE
```

##QDA
```{r qda}
library(MASS)

#Randomly shuffle the data
Customer_telecom<-Customer_telecom[sample(nrow(Customer_telecom)),]

#Create 10 equally size folds
folds <- cut(seq(1,nrow(Customer_telecom)),breaks=10,labels=FALSE)

MAE <- c()
mae <- c()

for (i in 1:10){
  testIndexes <- which(folds==i,arr.ind=TRUE)
  test_data <- Customer_telecom[testIndexes, ]
  train_data <- Customer_telecom[-testIndexes, ]
  m_qda <- qda(churn1 ~ number.vmail.messages + total.intl.calls + customer.service.calls, data = train_data)
  m_pred <- predict(m_qda, test_data)
  conf <- table(list(predicted=m_pred$class, observed=test_data$churn1))
  confusionMatrix(conf)
  print(conf)
  mae <- c(mae, mean(abs( as.integer(m_pred$class == 1) - as.integer(test_data$churn1 == 1))))
}

MAE=c(MAE, mean(mae))
MAE

```


